# NUMPY INTRODUCTION

In [1]:
# NUMPY is a python library function used for working with arrays
# it as also function for domain of linear algebra, fourier transforms and matrices.
# NUMPY is a numerical python.
# numpy as working with the array object in numpy is called ndarray.

In [7]:
import numpy        # importing numpy
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [8]:
import numpy as np  # importing numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [9]:
import numpy as np
print(np.__version__) # to check the version

1.26.4


In [10]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr)) # to check the type

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))  # list, tuple of methods can be converted as ndarray:
print(arr)

[1 2 3 4 5]


In [15]:
# dimensional in array
# a dimensional array is one level of the depth nested array

# 0-D array
import numpy as np
arr = np.array(42) 
print(arr)

42


In [16]:
# 1 -D Array
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [17]:
# 2 -D array
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [18]:
# 3 - D Array
import numpy as np
arr = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[3, 6, 9]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [3 6 9]]]


In [20]:
import numpy as np
a = np.array(42)
b = np.array([1, 2, 3, 4])
c = np.array([[1, 2, 3],[4, 5, 6]])
d = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[3, 6, 9]]])
print(a.ndim) # number of dimensions in array
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [21]:
# HIGHER DIMENSIONAL ARRAY
# you can define the number of dimensions by using the ndmin argument
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin = 5) # ndmin argument
print(arr)
print("number of dimensions in array:", arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions in array: 5


In [ ]:
# NUMPY ARRAY ELEMENTS
# Array indexing is e same as accessing an array elements
# you can access an array element by referring to its index number
# index numpy array start with the 0, as second digit as the 1 and so on...
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[1])
print(arr[2]+arr[3]) # addition of two elements

1
2
7


In [24]:
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6]])
print('2nd element on 1st row: ', arr[0, 1])
            # arr[first list of first index in, second index]

2nd element on 1st row:  2


In [26]:
import numpy as np
arr = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[3, 6, 9]]])
print(arr[0,1,2]) # 1st list 2nd list 3rd index

6


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6]])
print('print last element of last dimension:',arr[1,-1]) 

print last element of last dimension: 6


In [28]:
# NUMPY ARRAY SLICING
# SLICING ARRAYS [START:END:STEP]
# pass slice of index [start:end]
# can aslo defined a step [start:end:step]
# if don't pass start, default 0
# if don't pass end, default to end
# if don't pass step, default 1 

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr[1:5]) # 1 to 4 # step is by default 1
print(arr[0:])  # 1 to end
print(arr[:5])  # 0 to 4
print(arr[-3:-1]) # 4 to 5
print(arr[1:5:2])   # 1 to 4 with step 2
print(arr[1:6:4])   # 1 to 6 with step 4
print(arr[1:6:6])   # 1 to 6 with step 6
print(arr[::2]) # 0 to end with step 2

[2 3 4 5]
[1 2 3 4 5 6]
[1 2 3 4 5]
[4 5]
[2 4]
[2 6]
[2]
[1 3 5]


In [30]:
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr[1, 1:4]) 
print(arr[0, 1:4]) 
print(arr[0:2, 2])
print(arr[0:2, 1]) # end of index with both the array of index

[5 6]
[2 3]
[3 6]
[2 5]


In [31]:
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr[0:2, 1:4])
print(arr[0:3, 0:1]) 
print(arr[0:2, 0:2])
print(arr[0:3, 1:2]) # similar index to get the same dim if unsimilar the dim not applicable

[[2 3]
 [5 6]]
[[1]
 [4]]
[[1 2]
 [4 5]]
[[2]
 [5]]


In [34]:
# DATA TYPES IN PYTHON
# strings - ABCD
# integer - 1,2,3
# float - 1.2,3.4,5.3
# boolean - True, False
# complex - 1.0+2.0j

In [42]:
# DATA TYPES IN NUMPY
# i - integer
# b - boolean
# u - unsigned integer
# f - float 
# c - complex float
# m - timedelta
# M - datatime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type

# If you don’t specify dtype, NumPy will:
# Automatically infer the most general type that can represent all elements in the array.

In [43]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7]) # dtype by default is int
print(arr)
print(type(arr))
print(arr.dtype) # to check the data type

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
int64


In [44]:
import numpy as np
arr = np.array(['a', 'b', 'c', 'd']) # dtype by default is U1
print(arr)
print(arr.dtype) 

# '<U1' is NumPy's way of saying the array contains Unicode strings of length 1.
# Here's the breakdown:
# '<' = little-endian (irrelevant for strings, but part of NumPy's dtype format)
# 'U' = Unicode string
# '1' = maximum length of each string element (1 character)

['a' 'b' 'c' 'd']
<U1


In [48]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7], dtype = 'S') # S is 8 bit integer
print(arr)
print(type(arr))
print(arr.dtype) 

[b'1' b'2' b'3' b'4' b'5' b'6' b'7']
<class 'numpy.ndarray'>
|S1


In [49]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7], dtype = 'i4') # i4 is 32 bit integer
print(arr)
print(type(arr))
print(arr.dtype)

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
int32


In [52]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1]) # dtype by default is float
newarr = arr.astype('i')    # to change the data type to int32
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [53]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1]) # dtype by default is float
newarr = arr.astype('int') # to change the data type to int64
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [54]:
import numpy as np
arr = np.array([1.1, 0, 3.1]) # dtype by default is float
newarr = arr.astype(bool) # to change the data type to bool
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [55]:
# NUMPY ARRAY COPY VS VIEW
# copy:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy() # copy the array
arr[0] = 42 # change the first element of original array
print(arr) 
print(x) 

[42  2  3  4  5]
[1 2 3 4 5]


In [56]:
import numpy as np
# view:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view() # view the array
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [57]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[2] = 32
print(arr)
print(x)

[ 1  2 32  4  5]
[ 1  2 32  4  5]


In [60]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()

print(x.base) # base is the original array
print(y.base) # base is the original array

None
[1 2 3 4 5]


In [62]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
arr[2] = 42
print(arr)
print(x.base)
print(y.base)

[ 1  2 42  4  5]
None
[ 1  2 42  4  5]


In [64]:
# NUMPY IN ARRAY SHAPE
# shape of an array
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr.shape) # to check the shape # 2 rows and 3 columns

(2, 3)


In [66]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print('shape of array:',arr.shape)

shape of array: (4,)


In [67]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin = 5) # ndmin is number of dimension
print(arr)
print('shape of array:',arr.shape)

[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


In [69]:
# NUMPY IN RESHAPE
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4,3) # reshape the array to 4 rows and 3 columns
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [70]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(3,4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [75]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [73]:
# RETURN COPY OR VIEW
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base) # base is the original array

[1 2 3 4 5 6 7 8]


In [76]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 2, -1) # -1 will adjust the size automatically based on the number of elements
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [77]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(-1) 
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [78]:
# NUMPY ARRAY iterating
# iterating arrays
# multiple dimensions in numpy we use the for loop
import numpy as np
arr = np.array([1, 2, 3])
for x in arr:
    print(x)

1
2
3


In [79]:
# iterating 2-D arrays
import numpy as np
arr = ([[1, 2, 3],[4, 5, 6]])
for x in arr:
    print(x)

[1, 2, 3]
[4, 5, 6]


In [80]:
import numpy as np

arr = np.array([[1, 2, 3],[4, 5, 6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [7]:
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [81]:
# iterating 3-D array
import numpy as np
arr = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[3, 6, 9]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [3 6 9]]


In [82]:
import numpy as np 
arr = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[3, 6, 9]]])
for x in arr:
    for y in x:
        for z in x:
            print(z)

[1 2 3]
[4 5 6]
[1 2 3]
[4 5 6]
[7 8 9]
[3 6 9]
[7 8 9]
[3 6 9]


In [10]:
import numpy as np 
arr = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[3, 6, 9]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
3
6
9


In [83]:
# iterating arrays using nditer()
# nditer() very advanced function number of iterations
# iterating on each scalar element
import numpy as np
arr = np.array([[[1, 2],[3, 4]],[[5, 6],[7, 8]]])
for x in np.nditer(arr): # nditer() is used to iterate on each scalar element
    print(x)

1
2
3
4
5
6
7
8


In [87]:
# ITERATING ARRAY WITH DIFFERENT DATA TYPES
# OP_DTYPES 
import numpy as np
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags = ['buffered'], op_dtypes = ['S']): # S is for string, buffered is for buffering
    print(x) # type <class 'numpy.ndarray'>

b'1'
b'2'
b'3'


In [90]:
# skipping elements
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6]])
for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
4
6


In [92]:
# ENUMERATE is use as sequence of number
import numpy as np
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr): #returns the index and value
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [97]:
import numpy as np
arr = np.array(["rahul", "vinay", "raju", "pavan"])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) rahul
(1,) vinay
(2,) raju
(3,) pavan


In [100]:
# NUMPY JOINING ARRAY
# joining numpy arrays
# two are more arrays in a single array
# sequnece of array they want to join the concatenate()
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2)) # axis = 0 is for row by default
print(arr)

[1 2 3 4 5 6]


In [99]:
import numpy as np
arr1 = np.array([[1, 2],[3, 4]])
arr2 = np.array([[5, 6],[7, 8]])
arr = np.concatenate((arr1,arr2), axis = 1) # axis = 1 is for column
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [104]:
# JOING ARRAY USING STACK FUNCTIONS 
# STACKING IS AS SAME AS CONCATENATE
# THE ONLY DIFFERENCE IS THE NEW AXIS
import numpy as np
arr1 = ([1, 2, 3])
arr2 = ([4, 5, 6])
arr = np.stack((arr1, arr2), axis = 1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [105]:
# STACKING ALONG ROWS
# numpy provides a helper function: hstack() to
# stack along rows.
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [106]:
# STACKING ALONG colomn
# numpy provides a helper function: vstack() to
# stack along colomn.
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [107]:
# stacking along height (depth)
# dstack
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2)) 
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [109]:
# NUMPY SPLITING ARRAY
# SPLITTING NUMPY ARRAYS
# spliting is the reverse operation of the joinng 
# joining merges multiple arrays into one and splitting breaks one array into multiple.
# we use splitting array (array_split())
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3) # 3 is the number of array
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [110]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4) # 4 is the number of array
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [111]:
#splitting arrays
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [123]:
import numpy as np
arr = np.array([[1, 2],[3,4],[5, 6],[6, 7],[8, 9],[10, 11],[12, 13]])
newarr = np.array_split(arr, 3)
print(arr)

for ele in range(len(newarr)):
    print()
    print(newarr[ele].shape)
    print(newarr[ele])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]]

(3, 2)
[[1 2]
 [3 4]
 [5 6]]

(2, 2)
[[6 7]
 [8 9]]

(2, 2)
[[10 11]
 [12 13]]


In [124]:
import numpy as np
arr = np.array([[1, 2],[3,4],[5, 6],[6, 7],[8, 9],[10, 11],[12, 13]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4],
       [5, 6]]), array([[6, 7],
       [8, 9]]), array([[10, 11],
       [12, 13]])]


In [125]:
import numpy as np
arr = np.array([[1, 2, 4],[3, 4, 8],[5, 6, 7],[6, 7, 2],[8, 9, 7],[10, 11, 3],[12, 13, 4]])
newarr = np.array_split(arr, 3)
print(arr)

[[ 1  2  4]
 [ 3  4  8]
 [ 5  6  7]
 [ 6  7  2]
 [ 8  9  7]
 [10 11  3]
 [12 13  4]]


In [140]:
import numpy as np
arr = np.array([[1, 2, 4],[3, 4, 8],[5, 6, 7],[6, 7, 2],[8, 9, 7],[10, 11, 3],[12, 13, 4]])
newarr = np.array_split(arr, 5)
print(arr)

[[ 1  2  4]
 [ 3  4  8]
 [ 5  6  7]
 [ 6  7  2]
 [ 8  9  7]
 [10 11  3]
 [12 13  4]]


In [142]:
import numpy as np
arr = np.array([[1, 2, 4],[3, 4, 8],[5, 6, 7],[6, 7, 2],[8, 9, 7],[10, 11, 3],[12, 13, 4]])
newarr = np.array_split(arr, 5, axis = 1) # axis = 1 is for colomn
# print(newarr)
for ele in range(len(newarr)):
    print(newarr[ele])

[[ 1]
 [ 3]
 [ 5]
 [ 6]
 [ 8]
 [10]
 [12]]
[[ 2]
 [ 4]
 [ 6]
 [ 7]
 [ 9]
 [11]
 [13]]
[[4]
 [8]
 [7]
 [2]
 [7]
 [3]
 [4]]
[]
[]


In [146]:
# hsplit() is opposite to hstack()
import numpy as np
arr = np.array([[1, 2, 4],[3, 4, 8],[5, 6, 7],[6, 7, 2],[8, 9, 7],[10, 11, 3],[12, 13, 4]])
newarr = np.hsplit(arr, 3) 
print(newarr)

[array([[ 1],
       [ 3],
       [ 5],
       [ 6],
       [ 8],
       [10],
       [12]]), array([[ 2],
       [ 4],
       [ 6],
       [ 7],
       [ 9],
       [11],
       [13]]), array([[4],
       [8],
       [7],
       [2],
       [7],
       [3],
       [4]])]


In [149]:
# vstack() and dstack() is similar to
# vsplit() and dsplit()
import numpy as np
arr = np.array([[1, 2, 4],[3, 4, 8],[5, 6, 7],[6, 7, 2],[8, 9, 7],[10, 11, 3],[12, 13, 4]])
newarr = np.vsplit(arr, 7)

for ele in newarr:
    print(ele)

[[1 2 4]]
[[3 4 8]]
[[5 6 7]]
[[6 7 2]]
[[8 9 7]]
[[10 11  3]]
[[12 13  4]]


In [152]:
# NUMPY SEARCHING ARRAY
# Searching arrays
# you can a search a specific value we get the index value to find the number
# to search the array we use the where() method
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr == 4) # returns the index value which satisfies the condition
print(x)

(array([3]),)


In [155]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 7, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 7]),)


In [156]:
import numpy as np
arr = np.array([1, 2, 3, 4])
x = np.where(arr == 4)
print(x)

(array([3]),)


In [157]:
# WE FIND THE EVEN NUMBER FROM THE ARRAY
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7]),)


In [158]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6, 8]),)


In [159]:
# SEARCH SHORTED 
# searchsorted() to find its index value
import numpy as np
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1


In [161]:
# search form right side
import numpy as np
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side = 'right')
print(x)

2


In [163]:
import numpy as np
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


In [168]:
# NUMPY SORTING ARRAY
# SORTING ARRAY
# sort means putting elements in order sequence
# order sequence in numeric, alphabet, ascending or descending.
# the numpy ndarray object has a function called sort()
import numpy as np
arr = np.array([3, 6, 5, -6])
print(np.sort(arr)) # sort numerically

[-6  3  5  6]


In [169]:
import numpy as np
arr = np.array(["egg","apple","rinbow","cat","ball"])
print(np.sort(arr)) # sort alphabetically

['apple' 'ball' 'cat' 'egg' 'rinbow']


In [170]:
import numpy as np
arr = np.array(["flag","fight","from","for","fare"])
print(np.sort(arr)) 

['fare' 'fight' 'flag' 'for' 'from']


In [171]:
import numpy as np
arr = np.array([[1, 2],[3, 4]])
print(np.sort(arr)) 

[[1 2]
 [3 4]]


In [172]:
import numpy as np
arr = np.array([[1, 5, 2],[6, 4, 1]])
print(np.sort(arr))

[[1 2 5]
 [1 4 6]]


In [174]:
import numpy as np
arr = np.array([41, 42 , 43, 44])
x = [True, False, True, False]

newarr = arr[x]
print(newarr)

[41 43]


In [175]:
# creating the filter array
import numpy as np
arr = np.array([41, 42, 43, 44])

#create an empty list
filter_arr = []
# go through the elementin array
for element in arr:
    # if the element is heigher then the 42,
    # set the value to True, otherwise False:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
        
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [176]:
# craeting the filter array
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#craete an empty list
filter_arr = []

# go through the elementin array
for element in arr:
    # if the element is divisible by 2,
    # set the value to True, otherwise False:
    if element %2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
        
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False, True, False]
[2 4 6 8]


In [177]:
import numpy as np
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42 # returns a boolean array
newarr = arr[filter_arr] # returns the elements of the boolean array
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [178]:
import numpy as np
arr = np.array([41, 42, 43, 44])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True]
[42 44]
